# Introduction to Jupyter Notebooks

This notebook serves as a basic introduction to using Jupyter notebooks within the Netflix ETL project.  

- **Markdown cells** are used for explanatory text.  
- **Code cells** contain executable Python code.  

You can interleave narrative, visualizations, and code to explore data interactively.

In [1]:
# Simple demonstration of Python code in a notebook
import pandas as pd
import numpy as np

In [2]:
# create a small dataframe
df = pd.DataFrame({
    "A": np.random.randn(5),
    "B": np.random.randint(0, 10, size=5)
})

df

          A  B
0 -0.031695  9
1 -0.000210  8
2 -0.088618  6
3  0.481555  0
4 -0.392529  6

## Working with pandas DataFrame

Let's create a DataFrame representing students with columns:
- `student_id`
- `student_name`
- `age`

We'll populate it with sample data and display basic information and statistics.

In [3]:
import pandas as pd

# create student dataframe
students = pd.DataFrame([
    {"student_id": 1, "student_name": "Alice", "age": 20},
    {"student_id": 2, "student_name": "Bob", "age": 22},
    {"student_id": 3, "student_name": "Charlie", "age": 19},
    {"student_id": 4, "student_name": "Diana", "age": 21}
])

students

   student_id student_name  age
0           1        Alice   20
1           2          Bob   22
2           3      Charlie   19
3           4        Diana   21

In [4]:
# display basic info and statistics
print("DataFrame info:\n")
students.info()

DataFrame info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    4 non-null      int64
 1   student_name  4 non-null      object
 2   age           4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [5]:

print("\nDescriptive statistics:\n")
print(students.describe(include='all'))

Descriptive statistics:

        student_id student_name        age
count     4.000000            4   4.000000
unique         NaN            4        NaN
top            NaN        Alice        NaN
freq           NaN            1        NaN
mean      2.500000          NaN  20.500000
std       1.290994          NaN   1.290994
min       1.000000          NaN  19.000000
25%       1.750000          NaN  19.750000
50%       2.500000          NaN  20.500000
75%       3.250000          NaN  21.250000
max       4.000000          NaN  22.000000

## Handling Missing Values

We'll create a DataFrame containing some `NaN` / null values and
explore various pandas methods such as `.count()`, `.unique()`,
`.sum()`, `.isna()`, and applying custom functions.

In [6]:
import numpy as np

# DataFrame with missing values
students_na = pd.DataFrame({
    "student_id": [1, 2, 3, 4, np.nan],
    "student_name": ["Alice", None, "Charlie", "Diana", "Eve"],
    "age": [20, 22, np.nan, 21, 23]
})

students_na

   student_id student_name   age
0         1.0        Alice  20.0
1         2.0         None  22.0
2         3.0      Charlie   NaN
3         4.0        Diana  21.0
4         NaN          Eve  23.0

In [7]:
# Methods demonstration
print("Count of non-null values:\n", students_na.count(), "\n")

Count of non-null values:
 student_id      4
student_name    4
age             4
dtype: int64

In [8]:
print("Unique values (name):\n", students_na['student_name'].unique(), "\n")

Unique values (name):
 ['Alice' None 'Charlie' 'Diana' 'Eve']

In [9]:
print("Sum of student_id column (NaN treated as 0):\n", students_na['student_id'].sum(), "\n")

Sum of student_id column (NaN treated as 0):
 10.0

In [10]:
print("Isna matrix:\n", students_na.isna(), "\n")

Isna matrix:
    student_id  student_name    age
0       False         False  False
1       False          True  False
2       False         False   True
3       False         False  False
4        True         False  False

In [11]:
# apply function: add 10 to age if not null
print("\nApply function to age column:")
students_na['age_plus_10'] = students_na['age'].apply(lambda x: x + 10 if pd.notna(x) else x)
students_na

Apply function to age column:

   student_id student_name   age  age_plus_10
0         1.0        Alice  20.0         30.0
1         2.0         None  22.0         32.0
2         3.0      Charlie   NaN          NaN
3         4.0        Diana  21.0         31.0
4         NaN          Eve  23.0         33.0

## Working with DateTime

DateTime handling is crucial for data analysis. We'll explore:
- Creating datetime objects
- Parsing dates from strings
- DateTime operations in pandas DataFrames
- Formatting and extracting components

In [12]:
import pandas as pd
from datetime import datetime, timedelta

# Create datetime objects
now = datetime.now()
print("Current datetime:", now)

Current datetime: 2026-03-06 07:55:22.599015

In [13]:
# Parse dates from strings
date_str = "2023-10-15"
parsed_date = pd.to_datetime(date_str)
print("Parsed date:", parsed_date)

Parsed date: 2023-10-15 00:00:00

In [14]:
# DataFrame with datetime column
events = pd.DataFrame({
    "event": ["Start", "Mid", "End"],
    "date": pd.to_datetime(["2023-01-01", "2023-06-15", "2023-12-31"])
})

print("\nEvents DataFrame:")
print(events)

Events DataFrame:
   event       date
0  Start 2023-01-01
1    Mid 2023-06-15
2    End 2023-12-31

In [15]:
# Date operations
events['days_since_start'] = (events['date'] - events['date'].min()).dt.days
events['month'] = events['date'].dt.month
events['year'] = events['date'].dt.year

print("\nWith additional columns:")
print(events)

With additional columns:
   event       date  days_since_start  month  year
0  Start 2023-01-01                 0      1  2023
1    Mid 2023-06-15               165      6  2023
2    End 2023-12-31               364     12  2023

In [16]:

# Add days to a date
future_date = parsed_date + timedelta(days=30)
print(f"\n30 days after {parsed_date.date()}: {future_date.date()}")

30 days after 2023-10-15: 2023-11-14

## Understanding the `.apply()` Method

The `.apply()` method in pandas allows you to apply a function along an axis of the DataFrame (rows or columns). It's powerful for:
- Transforming data element-wise
- Performing calculations across rows/columns
- Applying custom logic to your data

Key parameters:
- `func`: The function to apply
- `axis`: 0 for columns, 1 for rows
- Can use lambda functions or named functions

In [17]:
import pandas as pd
import numpy as np

# Sample DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': ['a', 'b', 'c', 'd']
})

print("Original DataFrame:")
df

Original DataFrame:

   A   B  C
0  1  10  a
1  2  20  b
2  3  30  c
3  4  40  d

In [18]:
# Apply to columns (axis=0) - sum each column
print("\nSum of each column:")
print(df[['A', 'B']].apply(np.sum, axis=0))

Sum of each column:
A     10
B    100
dtype: int64

In [24]:
# Apply to rows (axis=1) - sum each row
print("\nSum of each row:")
df[['A', 'B']].apply(np.sum, axis=1)

Sum of each row:

0    11
1    22
2    33
3    44
dtype: int64

In [23]:
# Using lambda function - double values in column A
print("\nDouble values in column A:")
df['A_doubled'] = df['A'].apply(lambda x: x * 2)
df

Double values in column A:

   A   B  C  A_doubled
0  1  10  a          2
1  2  20  b          4
2  3  30  c          6
3  4  40  d          8

In [22]:
# Custom function - categorize ages
def categorize_age(age):
    if pd.isna(age):
        return 'Unknown'
    elif age < 20:
        return 'Teen'
    elif age < 25:
        return 'Young Adult'
    else:
        return 'Adult'

# Apply to the students_na DataFrame from earlier
students_na['age_category'] = students_na['age'].apply(categorize_age)
print("\nStudents with age categories:")
students_na[['student_name', 'age', 'age_category']]

Students with age categories:

  student_name   age age_category
0        Alice  20.0  Young Adult
1         None  22.0  Young Adult
2      Charlie   NaN      Unknown
3        Diana  21.0  Young Adult
4          Eve  23.0  Young Adult